### ISSUE TITLE
Changing server IP does work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jtilander/niftyplugins#103]
```
What steps will reproduce the problem?
1. Connect to a perforce server and do some operations
2. Change the IP of the setup dialog to another working server
3. try to checkout a file

What is the expected output? What do you see instead?
I would expect to have the file checked out.
Instead it tries to connect to the old server.

What version of the product are you using? On what operating system?
1.5, on VS2013, on Windows 7 64 bit.

Please provide any additional information below.


```

Original issue reported on code.google.com by `alessand...@gmail.com` on 7 Aug 2014 at 8:39

**Comment by jtilander** [comment]
This seems like a user setup error? Niftyperforce works through the P4CONFIG environment variable in most cases, since it just calls out to the p4.exe command with a carefully crafted current working directory. If you haven't setup the P4CONFIG, then it will just use the default server.
