### ISSUE TITLE
Integration for MSVC 2015

### ISSUE THREAD

**Issue by Weaseltron** [jtilander/niftyplugins#105]
It looks simple enough to bump the version number for MSVC to 14 and ship a new build as a previous commit did this for MSVC 2014 (version 13) in the following commit: fcb61353ebcad06d51db9464783ef4290e747206

**Comment by jtilander** [comment]
Apparently this doesn't work as 2015 removed the support for AddIns. So one has to make a full new plugin, as outlined in this issue here: https://github.com/jtilander/niftyplugins/issues/102
