### ISSUE TITLE
Newest version doesn't install on VS2013

### ISSUE THREAD

**Issue by A-t48** [jtilander/niftyplugins#107]
11/23/2015 2:34:08 PM - Microsoft VSIX Installer
11/23/2015 2:34:08 PM - -------------------------------------------
11/23/2015 2:34:08 PM - Initializing Install...
11/23/2015 2:34:08 PM - Extension Details...
11/23/2015 2:34:08 PM - 	Identifier      : NiftyPerforce.Tilander.eb29cef1-a8b5-41b1-922d-6ba8cec91ef4
11/23/2015 2:34:08 PM - 	Name            : NiftyPerforce
11/23/2015 2:34:08 PM - 	Author          : Jim Tilander
11/23/2015 2:34:08 PM - 	Version         : 2.0.0
11/23/2015 2:34:08 PM - 	Description     : Simple Perforce integration for Visual Studio
11/23/2015 2:34:08 PM - 	Locale          : en-US
11/23/2015 2:34:08 PM - 	MoreInfoURL     : https://github.com/jtilander/niftyplugins
11/23/2015 2:34:08 PM - 	InstalledByMSI  : False
11/23/2015 2:34:08 PM - 	SupportedFrameworkVersionRange : [4.5,)
11/23/2015 2:34:08 PM - 
11/23/2015 2:34:08 PM - 	Supported Products : 
11/23/2015 2:34:08 PM - 		Microsoft.VisualStudio.Community
11/23/2015 2:34:08 PM - 			Version : [11.0,15.0]
11/23/2015 2:34:08 PM - 		Microsoft.VisualStudio.Pro
11/23/2015 2:34:08 PM - 			Version : [11.0,15.0)
11/23/2015 2:34:08 PM - 
11/23/2015 2:34:08 PM - 	References      : 
11/23/2015 2:34:08 PM - 		-------------------------------------------------------
11/23/2015 2:34:08 PM - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
11/23/2015 2:34:08 PM - 		Name         : Visual Studio MPF 14.0
11/23/2015 2:34:08 PM - 		Version      : [14.0]
11/23/2015 2:34:08 PM - 		MoreInfoURL  : 
11/23/2015 2:34:08 PM - 		Nested       : No
11/23/2015 2:34:08 PM - 
11/23/2015 2:34:08 PM - 
11/23/2015 2:34:08 PM - Searching for applicable products...
11/23/2015 2:34:08 PM - Found installed product - Microsoft Visual Studio Professional 2013
11/23/2015 2:34:09 PM - The extension with ID 'NiftyPerforce.Tilander.eb29cef1-a8b5-41b1-922d-6ba8cec91ef4' is not installed to Microsoft Visual Studio Professional 2013.
11/23/2015 2:34:09 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
11/23/2015 2:34:09 PM - Found installed product - Global Location
11/23/2015 2:34:12 PM - The following target products have been selected...
11/23/2015 2:34:12 PM - 	Microsoft Visual Studio Professional 2013
11/23/2015 2:34:12 PM - 
11/23/2015 2:34:12 PM - Beginning to install extension to Microsoft Visual Studio Professional 2013...
11/23/2015 2:34:12 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Visual Studio MPF 14.0
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)

**Comment by jtilander** [comment]
Yeah, I guess expected as I compiled the plugin with VS2015. Perhaps if one compiled the plugin with a lower VS version, it would work on those as well?

**Comment by A-t48** [comment]
Negative - the projects won't downgrade back to VS2013.

**Comment by amaiorano** [comment]
Does this also fix the same problem with VS 2012 install? Also, can we get a new release with this fix in it? Thanks!

**Comment by A-t48** [comment]
I don't have 2012 installed at the moment (2008, 2013, 2015 is too much already!)

I agree, 1.5.1 would be smart.

**Comment by amaiorano** [comment]
Ah, well I assume if it installs on 2008, 2013, and 2015, it should install on 2012 as well :)

Would you happen to have a .vsix available for me to try?

**Comment by A-t48** [comment]
I don't have it installed on 2008 (only have Express, no plugins allowed).

This _might_ work. I just ran 'makedist.cmd' and it seems to come out ok. :)
[NiftyPerforce.zip](https://github.com/jtilander/niftyplugins/files/87726/NiftyPerforce.zip)

**Comment by amaiorano** [comment]
Thanks, A-t48, I can confirm that it installs for VS 2012, 2013, and 2015.

Unrelated, but there's still the "toolbar bug" (Nifty somehow hijacks/merges into another extension's toolbar, and the nifty buttons are all disabled. This bug has been there for a long time).

Anyway, thanks!

**Comment by A-t48** [comment]
@amaiorano do you have a workaround for that toolbar bug? I'm hitting it at home, and it's causing it to be impossible to configure nifty.

**Comment by amaiorano** [comment]
Unfortunately, no, I don't have a workaround for this toolbar bug. Sad to say, but despite having used Nitfty for many years, I've moved on to [another plugin](https://visualstudiogallery.msdn.microsoft.com/8e2bcfc4-a847-4c53-80af-7d91f6faab2b) that seems to work well enough :/
