### ISSUE TITLE
Visual Studio 2013 Broken?

### ISSUE THREAD

**Issue by cowbs** [jtilander/niftyplugins#113]
Did the latest version break support for Visual Studio 2013? After installing the latest version all the toolbar icons are greyed out and all the commands, while registered, are unavailable. 

I've tried everything I can think of to give the plugin a clean slate to try working from, including uninstalling and wiping all the settings, but still no luck.

Any help is appreciated, thanks!

**Comment by jtilander** [comment]
Yepp! I think once I released the VS2015 support I killed the previous versions. Just download an older version, very little changed in the code since. Most of the changes have been for VS2015 support.

**Comment by jtilander** [comment]
This version should work for you:

https://github.com/jtilander/niftyplugins/releases/tag/1.6.0

**Comment by cowbs** [comment]
Okay. Yeah looks like installing the latest vsix on top of that .msi-installed version is where things went downhill for me. Maybe change the .vsixmanifest so support begins at vs2015? I don't know github well enough to make a pull request but it would be these lines in [source.extension.vsixmanifest](https://github.com/jtilander/niftyplugins/blob/master/NiftyPerforce/source.extension.vsixmanifest):

`    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0,15.0]" />
    <InstallationTarget Version="[14.0,15.0)" Id="Microsoft.VisualStudio.Pro" />`
