### ISSUE TITLE
Niftyperforce doesn't respect the correct case for CTRL-E, but for project item edit.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jtilander/niftyplugins#18]
```
For case sensitive perforce servers, case is important for checking out.

It seems that the normal EDIT action mangles the case somehow, but not for
the project item edit. 
```

Original issue reported on code.google.com by `jim.tila...@gmail.com` on 21 Aug 2008 at 6:21

**Comment by jtilander** [comment]
Now that the -C1 flag (case insensitivity) is official, that really should be the way you have your server configured. Basically all other ways lead to grief, suffering and pain.
