### ISSUE TITLE
NiftyPerforce "finds" perforce executable in wrong directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jtilander/niftyplugins#71]
```
What steps will reproduce the problem?
1. Open perforce controlled project (you can see in output window)
2. Any time a perforce operation is attempted, get an error saying the 
executable cannot be found in the perforce directory.
3.

What is the expected output? What do you see instead?
I am running 64-bit windows, and I have p4v installed in Program 
Files\Perforce.  Nifty reports that it finds p4 in Program Files(x86)\Perforce

What version of the product are you using? On what operating system?
NiftyPerforce v1.3.1. Windows 7 64-bit, Visual Studio 2008, Rev. Perforce 
Visual Client/NTX86/2010.1/276058

Please provide any additional information below.

Attached captures of output window and error.

```

Original issue reported on code.google.com by `bardic...@gmail.com` on 28 Jun 2011 at 9:43

Attachments:
* [niftyperforce_error.jpg](https://storage.googleapis.com/google-code-attachments/niftyplugins/issue-71/comment-0/niftyperforce_error.jpg)
* [NiftyPerforce_output.jpg](https://storage.googleapis.com/google-code-attachments/niftyplugins/issue-71/comment-0/NiftyPerforce_output.jpg)

**Comment by jtilander** [comment]
I believe that I "fixed" this in commit 9967d5a7125fd9eb400cb8d7f604cdacd3f1d763 with the new logic to just search the default directories first -- and choose the 64 bit directory by default. This assumes that you have p4v and p4win in the 64 bit directory together (even though p4win is a 32 bit executable). Well, you really should have niftyp4win installed :)
